### ISSUE TITLE
Guideline Conformance

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#15]
Guidelines are great as long as they are followed. How are we going to measure and improve guideline conformance?

**Comment by rsahlstrom** [comment]
Pull requests and code reviews. @deseretdigital-ui/front-end-developers

**Comment by jehoshua02** [comment]
I would like a "Code Review Checklist" in that case.

**Comment by rsahlstrom** [comment]
Like this?
- Review use of CSS Guidelines?

**Comment by jehoshua02** [comment]
A good set of guidelines is a checklist in and of itself really.

**Comment by rsahlstrom** [comment]
That said, if there's some tool that can help, I'm all for it. I plan on using jshint to help enforce our JS guidelines when we agree on them. Maybe there's something like that for css.
