### ISSUE TITLE
Minimum Dimensions for Clickable Elements

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#22]
With touch devices we have to be careful all clickable items accommodate fat fingers.

Does something like this belong in CSS Guidelines? Maybe it's too "design" related?

**Before Closing Issue:**
- [x] Response from @jstoutenburg
- [x] Response from @janiv
- [ ] Response from @kbratko
- [ ] Response from @jspencerDDM
- [ ] Response from @hhatfield
- [ ] Consensus or Decision
- [ ] Pull request or other action if necessary

**Comment by rsahlstrom** [comment]
I think this is more design.

**Comment by jehoshua02** [comment]
I thought so. Some day maybe we'll have guidelines for that kind of stuff too.

I'll close this for now.
