### ISSUE TITLE
Critical Thinking: Build? Reuse? Copy/Paste?

### ISSUE THREAD

**Issue by jehoshua02** [deseretdigital-ui/CSS-Guidelines#23]
We need to be more careful about copying and pasting and thinking more deeply about what we are doing. When coding up a design, we should really consider if we've seen something like it before, and if we have, take the time to decide if and what we can abstract and reuse instead of copy/paste, or worse, code it from scratch again. I don't want to write from scratch or copy/paste things we could abstract and reuse. But at the same time I don't want to abstract the wrong things. Critical Thinking is required.

Do the guidelines need to speak more about any of these concerns?

**Before Closing Issue:**
- [x] Response from @jstoutenburg
- [x] Response from @janiv
- [ ] Response from @kbratko
- [ ] Response from @jspencerDDM
- [ ] Response from @hhatfield
- [ ] Consensus or Decision
- [ ] Pull request or other action if necessary

**Comment by rsahlstrom** [comment]
Are there things not covered in the section http://cssguidelin.es/#architectural-principles that you're concerned about specifically?

**Comment by rsahlstrom** [comment]
Here's the sub-sections.

![screen shot 2014-11-14 at 12 59 00 pm](https://cloud.githubusercontent.com/assets/677780/5052493/0f698e3a-6bfe-11e4-9f32-e112ec941ebf.png)

**Comment by jehoshua02** [comment]
I think DRY covers it. Closing issue.
